/* Generated by re2c 0.13.5 on Sun Aug 25 00:27:48 2013 */
#include <stdio.h>
#include <string.h>

unsigned char checkinput(char* s)
{
    char *q;

{
        char yych;

        yych = *s;
        switch (yych) {
        case 'H':       goto yy2;
        default:        goto yy4;
        }
yy2:
        yych = *(q = ++s);
        switch (yych) {
        case 'i':       goto yy5;
        default:        goto yy3;
        }
yy3:
        { return 0; }
yy4:
        yych = *++s;
        goto yy3;
yy5:
        yych = *++s;
        switch (yych) {
        case '-':       goto yy7;
        default:        goto yy6;
        }
yy6:
        s = q;
        goto yy3;
yy7:
        yych = *++s;
        switch (yych) {
        case '0':
        case '1':
        case '2':
        case '3':
        case '4':
        case '5':
        case '6':
        case '7':
        case '8':
        case '9':       goto yy8;
        default:        goto yy6;
        }
yy8:
        yych = *++s;
        switch (yych) {
        case '0':
        case '1':
        case '2':
        case '3':
        case '4':
        case '5':
        case '6':
        case '7':
        case '8':
        case '9':       goto yy9;
        default:        goto yy6;
        }
yy9:
        yych = *++s;
        switch (yych) {
        case '0':
        case '1':
        case '2':
        case '3':
        case '4':
        case '5':
        case '6':
        case '7':
        case '8':
        case '9':       goto yy10;
        default:        goto yy6;
        }
yy10:
        yych = *++s;
        switch (yych) {
        case '0':
        case '1':
        case '2':
        case '3':
        case '4':
        case '5':
        case '6':
        case '7':
        case '8':
        case '9':       goto yy11;
        default:        goto yy6;
        }
yy11:
        ++s;
        { return 1; }
}

}

int main(int argc, char *argv[])
{
    if(argc != 2)
    {
        printf("./fsm <string>\n");
        return 0;
    }

    if(checkinput(argv[1]))
        printf("Good boy.\n");
    else
        printf("Bad boy.\n");

    return 1;
}
